#Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- mega2560 ide 1.0
BOARD_TAG    = nano328
ARDUINO_PORT = /dev/ttyUSB0 
ARDUINO_LIBS = Wire
include /usr/share/arduino/Arduino.mk

