#Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- mega2560 ide 1.0
BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB2 
ARDUINO_LIBS = SHT1x Wire SPI RF24-master
include /usr/share/arduino/Arduino.mk

