#Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- mega2560 ide 1.0
BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyUSB0 
ARDUINO_LIBS = SHT1x Wire
include /usr/share/arduino/Arduino.mk

